CREATE TABLE IF NOT EXISTS flag (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    `key` VARCHAR(200) NOT NULL UNIQUE,
    name VARCHAR(500),
    description TEXT,
    flag_type VARCHAR(20) NOT NULL DEFAULT 'BOOLEAN',
    default_value TEXT NOT NULL DEFAULT 'false',
    enabled BOOLEAN DEFAULT FALSE,
    release_version VARCHAR(100),
    app_name VARCHAR(100) NOT NULL,
    created_by VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
